### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by emilyaviva** [Coders-Living-Instant-Work-Journal/coders-living-instant-journal-client#59]
## Repository
- Good `README` file

## Prompts/Inquirer
- I'm super proud of your use of `inquirer` to prompt the user for input. You went above and beyond, basically creating an entire front-end for this app that works on the command line. Well done learning to use a new API and implementing an end-to-end solution!
- There are a few rough edges in how the app handles various situations: for example, it'd be nice to have it remain open in certain places—it seems to "quit" and then clear my screen when I'm not expecting that to happen, even though the action I did is done—like you can only do one action at a time.
- Regardless, fantastic job getting to—and past!—MVP.
- You can remove `minimist` as a dependency of this project, since you're not using it.

## Tests
- Mocking command-line input is a PITA, for sure. Like I said for the API, to really "battle-harden" this app, you'll want to do some integration testing, making sure that the command-line really functions the way you expect it to.

**Comment by eugenemonnier** [comment]
Thanks for the feedback. A quick note on how the app quits. In most cases, we are expecting that the user will want to do one thing (create/delete/read/update an entry) and then get back to whatever they were doing quickly. I can imagine that maybe in the case of creating a new journal or selecting a different journal, the user might want to be brought back to the main screen so they can CRUD entries for that journal.

The client app shouldn't clear your screen. All previous work done on the command line should be above where you called CLIJ if you scroll.
